### PR TITLE
Remove wget dependency

### PR DESCRIPTION
**Pull request by Bomme**
Since wget is not well maintained, I implemented this download functionality along the lines of gdown's download method. Since the project already depends on requests and tqdm no new dependenies are introduced.

### CODE REVIEW

**Comment by dbogdanov** [comment]
Can you provide more info about the status of wget?

One thing to keep in mind is that wget retries the downloads multiple times, which may be useful for slow unreliable network connections, especially as the downloads from our server are slow. We could add as similar retry functionality.

**Comment by Bomme** [comment]
I mostly implemented this to see if we can get some benefit of using requests. So this is only a suggestion and not something that we need to change.
>Can you provide more info about the status of wget?

If I'm interpreting it right wget [was not updated since 2015](https://pypi.org/project/wget/#history)

>One thing to keep in mind is that wget retries the downloads multiple times, which may be useful for slow unreliable network connections, especially as the downloads from our server are slow. We could add as similar retry functionality.

I'm not convinced that wget will retry downloads. It simply uses urlretrieve which is part of the [legacy interface](https://docs.python.org/3.8/library/urllib.request.html#legacy-interface). 

<details>
  <summary>Since I cannot find the code for wget online I'll put the releveant function here:</summary>
  
wget 3.2

  ```python
  def download(url, out=None, bar=bar_adaptive):
    """High level function, which downloads URL into tmp file in current
    directory and then renames it to filename autodetected from either URL
    or HTTP headers.

    :param bar: function to track download progress (visualize etc.)
    :param out: output filename or directory
    :return:    filename where URL is downloaded to
    """
    # detect of out is a directory
    outdir = None
    if out and os.path.isdir(out):
        outdir = out
        out = None

    # get filename for temp file in current directory
    prefix = detect_filename(url, out)
    (fd, tmpfile) = tempfile.mkstemp(".tmp", prefix=prefix, dir=".")
    os.close(fd)
    os.unlink(tmpfile)

    # set progress monitoring callback
    def callback_charged(blocks, block_size, total_size):
        # 'closure' to set bar drawing function in callback
        callback_progress(blocks, block_size, total_size, bar_function=bar)
    if bar:
        callback = callback_charged
    else:
        callback = None

    if PY3K:
        # Python 3 can not quote URL as needed
        binurl = list(urlparse.urlsplit(url))
        binurl[2] = urlparse.quote(binurl[2])
        binurl = urlparse.urlunsplit(binurl)
    else:
        binurl = url
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
    filename = detect_filename(url, out, headers)
    if outdir:
        filename = outdir + "/" + filename

    # add numeric ' (x)' suffix if filename already exists
    if os.path.exists(filename):
        filename = filename_fix_existing(filename)
    shutil.move(tmpfile, filename)

    #print headers
    return filename
  ```
  
</details>

**Comment by Bomme** [comment]
I just realised that there might be a missunderstanding: The `wget` in this project is a [python package](https://pypi.org/project/wget/) that just borrows the name from the [Unix tool](https://linux.die.net/man/1/wget). So there is no connection between the two.

**Comment by alastair** [comment]
In response to #46, I think that we should take this PR into consideration again. I agree with @Bomme that the `wget` python package has nothing to do with the actual wget tool, and we should go with something like requests instead (unless we can find another package which actually does wget-style retrying and file checking).

**Review by dbogdanov — APPROVED** [review]

**Pull request merged**
